config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :products
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image 
  include Neo4j::ActiveNode
  include Neo4jrb::Paperclip
  property :name, type: String
  property :description, type: String
  property :ingested_path, type: String


  property :normalized_name, type: String
  validates_presence_of :name
  validate :set_normalized_name

  private
  def set_normalized_name
    self.normalized_name = self.name.downcase if self.name
  end

  public
  has_neo4jrb_attached_file :image_file, styles: {thumbnail: "110x110#"}, :convert_options => { :thumb => "-quality 60 -strip" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\Z/

  has_one :in, :product, type: :PRODUCT_IMAGE, model_class: :Product
  has_many :both, :other_versions, type: :OTHER_VERSION, model_class: :Image

end

app/models/product.rb
class Product 
  include Neo4j::ActiveNode
  property :name, type: String
  property :description, type: String
  property :sku, type: String

  property :normalized_name, type: String
  validates_presence_of :name
  validate :set_normalized_name

  private
  def set_normalized_name
    self.normalized_name = self.name.downcase if self.name
  end

  public
  has_many :out, :tags, type: :TAGGED, model_class: :Tag
  has_many :both, :relateds, type: :RELATED, model_class: :Product
  has_many :out, :product_images, type: :PRODUCT_IMAGE, model_class: :Image
  

end

app/models/tag.rb
class Tag 
  include Neo4j::ActiveNode
  property :name, type: String

  property :normalized_name, type: String
  validates_presence_of :name
  validate :set_normalized_name

  private
  def set_normalized_name
    self.normalized_name = self.name.downcase if self.name
  end

  public
  has_many :in, :tagged, type: :RELATED, model_class: :Tag

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to @image, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to @image, notice: 'Image was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy
    redirect_to images_url, notice: 'Image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def image_params
                              
      params.require(:image).permit( :name, :description, :ingested_path, :normalized_name, :image_file, :product, :other_versions => [] )
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
                              
      params.require(:product).permit( :name, :description, :sku, :normalized_name, :tags => [], :relateds => [], :product_images => [] )
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
                              
      params.require(:tag).permit( :name, :normalized_name, :tagged => [] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text) #Allows the ability to render markdown inline. Example: `<%= markdown(@artefact.content) %>`
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: "nofollow", target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/images/_form.html.erb
<div class="ui text container">
  <div class="ui form">
    <%= form_for(@image) do |f| %>
      <% if @image.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
          <ul>
            <% @image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

            <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.label "Image File" %><br>
              <%= f.file_field :image_file %>
            </div>
          
            <div class="field">
              <%= f.label :description %><br>
              <%= f.text_field :description %>
            </div>
          
            <div class="field">
              <%= f.label :ingested_path %><br>
              <%= f.text_field :ingested_path %>
            </div>
         
            <div class="field">
              <%= f.label :product_id %><br>
                
              <% if @image.product %>
                <%= f.collection_select(:product, Product.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @image.product.id}, html_options = {:multiple => false, :class=>"search"}) %>
              <% else %>
                <%= f.collection_select(:product, Product.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item"}, html_options = {:multiple => false, :class=>"search"}) %>
              <% end %>
            </div>

         
            <div class="field">
              <%= f.label :other_versions_id %><br>
              
              <%= f.collection_select(:other_versions, Image.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @image.other_versions.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
            </div>


      <div class="actions">
        <%= f.submit html_options = {:class=>"ui button"}%>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.search')
  .dropdown()
;
</script>

<script>
$('.ui.form')
  .form({
    fields: {
      image_name     : 'empty',
    }
  })
;
</script>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui very padded container ">
  <h1>Images</h1>

  <table class="ui very basic celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Ingested path</th>
        <th>Product</th>
        <th>Other versions</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @images.limit(45).each do |image| %>
        <tr>
          <td>
            <%- if !image.name.nil? %>
              <%= link_to image.name, image %>
            <%- end %>
          </td>
          <td>
            <%- if !image.description.nil? %>
              <%= image.description %>
            <%- end %>
          </td>
          <td>
            <%- if !image.ingested_path.nil? %>
              <%= image.ingested_path %>
            <%- end %>
          </td>
          <td>
            <%- if !image.product.nil? %>
              <%= link_to image.product.name, image.product %>
            <%- end -%>
          </td>
          <td>
            <%- if !image.other_versions.nil? %>
              <%- image.other_versions.each do |other_versions| -%>
                <%= link_to other_versions.name, other_versions %>
              <%- end -%>
            <%- end -%>
          </td>
          <td><%= link_to 'Show', image %></td>
          <td><%= link_to 'Edit', edit_image_path(image) %></td>
          <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Image', new_image_path %>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui container">
  <a class="ui labeled icon button" href="<%= images_path %>">
    <i class="up arrow icon"></i>
    List Images
  </a>
  <a class="ui basic icon button" href="<%= edit_image_path(@image) %>">
    <i class="edit icon"></i>
    Edit
  </a>
</div>

<div class="ui hidden divider"></div>

<div class="ui text container">
  <h1 class="ui dividing header">Image</h1>
</div>

<div class="ui text container">
  <p>
    <strong>Name:</strong>
    <%= @image.name -%>
  </p>
  <%= image_tag(@image.image_file.url, :class =>"ui very padded fluid image")  %>
  <p>
    <strong>Description:</strong>
    <%= @image.description -%>
  </p>
  <p>
    <strong>Ingested path:</strong>
    <%= @image.ingested_path -%>
  </p>
  <p>
    <strong>Product:</strong>
    <% if !@image.product.nil? -%>
      <%= link_to @image.product.name, @image.product %>
    <% end -%>
  </p>
  <p>
    <strong>Other versions:</strong>
    <% if !@image.other_versions.nil? -%>
      <% @image.other_versions.each do |other_versions| -%>
        <%= link_to other_versions.name, other_versions %>
      <% end -%>
    <% end -%>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>PhotoTestTemplates</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <link rel="stylesheet" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/components/form.min.css">
    <link rel="stylesheet" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/components/dropdown.min.css">
    <link rel="stylesheet" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/semantic.min.css">
    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/semantic.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/components/form.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/components/dropdown.min.js"></script>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="ui stackable container menu">
      <div class="header item">
        eIMS
      </div>
      <a class="item" href="/products/">
        Products
      </a>
      <a class="item" href="/images/">
        Images
      </a>
      <a class="item" href="/tags/">
        Tags
      </a>
    </div>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="ui text container">
  <div class="ui form">
    <%= form_for(@product) do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>

      <div class="field">
        <%= f.label :sku %><br>
        <%= f.text_field :sku %>
      </div>

      <div class="field">
        <%= f.label :tags_id %><br>

        <%= f.collection_select(:tags, Tag.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @product.tags.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
      </div>

   
      <div class="field">
        <%= f.label "Related Products" %><br>
        
        <%#= f.collection_select(:relateds, Product.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @product.relateds.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
      </div>

      <div class="field">
        <%= f.label :product_images_id %><br>
        
        <%= f.collection_select(:product_images, Image.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @product.product_images.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
      </div>


      <div class="actions">
        <%= f.submit html_options = {:class=>"ui button"}%>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.search')
  .dropdown({
    fullTextSearch: true,
  )}
;
</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui very padded container ">
  <h1>Products</h1>

  <table class="ui very basic celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Sku</th>
        <th>Tags</th>
        <th>Related Products</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.limit(45).each do |product| %>
        <tr>
          <td>
            <%- if !product.name.nil? %>
              <%= link_to product.name, product %>
            <%- end %>
          </td>
          <td>
            <%- if !product.description.nil? %>
              <%= product.description %>
            <%- end %>
          </td>
          <td>
            <%- if !product.sku.nil? %>
              <%= product.sku %>
            <%- end %>
          </td>
          <td>
            <%- if !product.tags.nil? %>
              <%- product.tags.each do |tags| -%>
                <%= link_to tags.name, tags %>
              <%- end -%>
            <%- end -%>
          </td>
          <td>
            <%- if !product.relateds.nil? %>
              <%- product.relateds.each do |relateds| -%>
                <%= link_to relateds.name, relateds %>
              <%- end -%>
            <%- end -%>
          </td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui container">
  <a class="ui labeled icon button" href="<%= products_path %>">
    <i class="up arrow icon"></i>
    List Products
  </a>
  <a class="ui basic icon button" href="<%= edit_product_path(@product) %>">
    <i class="edit icon"></i>
    Edit
  </a>
</div>

<div class="ui hidden divider"></div>

<div class="ui text container">
  <h1 class="ui dividing header">Product</h1>
</div>

<div class="ui text container">
  <p>
    <strong>Name:</strong>  <%= @product.name -%></br>
  </p>
  <p>
    <strong>Description:</strong>
    </br>
    <%= @product.description -%>
  </p>
  <p>
    <strong>Sku:</strong> <%= @product.sku -%></br>
  </p>

  <p>
    <strong>Product Images:</strong>
    <div class="ui four column doubling cards container">
      <% if !@product.product_images.nil? -%>
        <% @product.product_images.each do |product_image| -%>
          <div class="ui card">
            <div class="image">
              <%= image_tag product_image.image_file.url(:thumbnail) %>
            </div>
            <div class="extra">
              <%= link_to product_image.name, product_image %>
            </div>
          </div>
        <% end -%>
      <% end -%>
    </div>
  </p>

  
    <p>
    <strong>Tags:</strong>
    <% if !@product.tags.nil? -%>
      <% @product.tags.each do |tags| -%>
        <%= link_to tags.name, tags %>
      <% end -%>
    <% end -%>
    </br>
  </p>

    <p>
    <strong>Related products:</strong>
    <% if !@product.relateds.nil? -%>
      <% @product.relateds.each do |relateds| -%>
        <%= link_to relateds.name, relateds %>
      <% end -%>
    <% end -%>
    </br>
      </p>
</div>

app/views/tags/_form.html.erb
<div class="ui text container">
  <div class="ui form">
    <%= form_for(@tag) do |f| %>
      <% if @tag.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
          <ul>
            <% @tag.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      
                              <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
          
              
                              <div class="field">
              <%= f.label :normalized_name %><br>
              <%= f.text_field :normalized_name %>
            </div>
          
              
                           
            <div class="field">
              <%= f.label :tagged_id %><br>
              
              <% if @tag.tagged %>
                <%= f.collection_select(:tagged, Tag.all.sort { |a,b| a.name <=> b.name }, :id, :name, options = {:prompt => "Please Select an Item", :selected => @tag.tagged.map(&:id)}, html_options = {:multiple => true, :class=>"search"}) %>
              <% end %>
            </div>
          
              
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.search')
  .dropdown()
;
</script>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui very padded container ">
  <h1>Tags</h1>

  <table class="ui very basic celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Tagged</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tags.limit(45).each do |tag| %>
        <tr>
          <td>
            <%- if !tag.name.nil? %>
              <%= tag.name %>
            <%- end %>
          </td>
          <td>
            <%- if !tag.tagged.nil? %>
              <%- tag.tagged.each do |tagged| -%>
                <%= link_to tagged.name, tagged %>
              <%- end -%>
            <%- end -%>
          </td>
          <td><%= link_to 'Show', tag %></td>
          <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
          <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Tag', new_tag_path %>
</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui container">
  <a class="ui labeled icon button" href="<%= tags_path %>">
    <i class="up arrow icon"></i>
    List Tags
  </a>
  <a class="ui basic icon button" href="<%= edit_tag_path(@tag) %>">
    <i class="edit icon"></i>
    Edit
  </a>
</div>

<div class="ui hidden divider"></div>

<div class="ui text container">
  <h1 class="ui dividing header">Tag</h1>
</div>

<div class="ui text container">
  <p>
    <strong>Name:</strong>
    <%= @tag.name -%>
  </p>
  <p>
    <strong>Normalized name:</strong>
    <%= @tag.normalized_name -%>
  </p>
  <p>
    <strong>Tagged:</strong>
    <% if !@tag.tagged.nil? -%>
      <% @tag.tagged.each do |tagged| -%>
        <%= link_to tagged.name, tagged %>
      <% end -%>
    <% end -%>
  </p>
</div>